[ {
"poster":"https://dopaminevoice.kz/img/aot_poster_1.jpg",
"title":"Титандар Шабуылы",
"title_orignal":"進撃の巨人, Shingeki no Kyojin",
"age":"18+",
"country":"Жапония, 2013 жыл",
"i_video":"10/25 бөлім. ~25 минут",
"status":"Көп бөлімді, шықты",
"studio":"Студия Wit Studio, автор Исаяма Хадзимэ",
"note":"Аниме дубляжы уақытша тоқтатылды.\nТолық ақпаратты осы жерден біле аласыздар: <u>t.me/dopamine_voice</u>",
"info":"Көптеген жылдар бойы адамзат титандармен - ерекше ақыл-ойы жоқ, бірақ адамдарды жеп, одан ләззат алатын алып тіршілік иелерімен күресіп келеді. Ұзақ күрестен кейін адамзаттың қалдықтары титандар өте алмайтын, адамдар елін қоршап тұратын биік қабырғаларды тұрғызды. Содан бері жүз жыл өтті, адамдар қабырға қорғауында бейбіт өмір сүруде. Бірақ бір күні жасөспірім Эрен мен оның туысы Микаса қорқынышты оқиғаға тап болды - қабырғаның бір бөлігін кенет пайда болған алып титан қиратады. Титандар қалаға шабуыл жасайды, ал балалар титандардң бірі Эреннің анасын тірідей жеп жатқанына куә болды. Эрен барлық титандарды өлтіріп, адамзат үшін кек алатынына ант береді.",
"unavailable":"null",
"comments":"https://vk.com/widget_comments.php?app=8140038&amp;width=100%25&amp;_ver=1&amp;limit=15&amp;height=0&amp;mini=auto&amp;norealtime=0&amp;page=0&amp;status_publish=0&amp;attach=&amp;url=https%3A%2F%2Fdopaminevoice.kz%2Fchainsawman_1-1&amp;title=%D0%A8%D1%8B%D0%BD%D0%B6%D1%8B%D1%80%D0%BB%D1%8B%20%D0%90%D1%80%D0%B0%20%D0%90%D0%B4%D0%B0%D0%BC%201-%D0%9C%D0%B0%D1%83%D1%81%D1%8B%D0%BC%20%7C%20Dopamine%20Voice&amp;description=Dopamine%20Voice%20-%20%231%20%D2%9A%D0%B0%D0%B7%D0%B0%D2%9B%D1%88%D0%B0%20%D0%90%D0%BD%D0%B8%D0%BC%D0%B5%20%D1%81%D0%B0%D0%B9%D1%82%D1%8B.&amp;image=&amp;startWidth=363&amp;referrer=&amp;185e48852ea",
"height":"5000",
"description":"фэнтези, экшн, хоррор",
"uncom":"null",
"announcement":"null",
"data":"null",
"id":"attack-on-titan"
} ]
