[ {
"poster":"https://sun9-27.userapi.com/impg/ExyKIzaNdbqPgVyKxGt1omWJ41a5CtGiPebgwQ/CIr4zJL5fr8.jpg?size=403x604&quality=95&sign=3a11c39a80c0ae4a8dc808737367998b&type=album",
"title":"Вольт",
"title_orignal":"bolt",
"age":"0+",
"works":"usa",
"country":"АҚШ, 2008 жыл",
"i_video":"1 бөлім. ~96 минут",
"status":"Толықметражды, шықты",
"studio":"Режиссёр Байрон Ховард, Крис Уилямс",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"",
"note_li":"null",
"info":"Вольт есімді күшік өмір бойы телевидиялық хикаяға түсіп келеді, ол батыр — суперкүшік — тылсым күшін пайдаланып, адамзат баласын құтқарып келеді деп өзі соған сенеді, Алайда телехикая барысында Вольт кіші қорапқа талып түсіп, оянғанда қауіпті үлкен қалаға тап болады күшігіміздің тымсым күшін әрі қарай Dopamine қосымшасынан тамашалай аласыздар...",
"player":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"bolt",
"height":"null",
"uncom":"null",
"id":"bolt",
"data":"null",
"description":"отбасылық"
} ]
