[ {
"poster":"https://m.media-amazon.com/images/M/MV5BNjRiNmNjMmMtN2U2Yi00ODgxLTk3OTMtMmI1MTI1NjYyZTEzXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg",
"title":"Ажал дәптері",
"title_orignal":"Death Note",
"age":"18+",
"country":"Жапония, күз 2006 жыл",
"i_video":"37 бөлім. ~23 минут",
"status":"Көп бөлімді, шықты",
"studio":"Студия Madhouse, автор Цугуми Оба",
"note":"null",
"note_li":"null",
"info":"Орта мектеп оқушысы Лайт Ягамиге Ажал қызметшісі, яғни Шинигами, Рюктің дәптері қолына түседі. Осы дәптерге аты жазылған әрбір адам өледі, сондықтан Лайт Ягами жер бетіндегі зұлымдықпен күресуді шешеді.",
"player":"null",
"unavailable":"null",
"premium":"null",
"comments":"null",
"key":"death-note",
"height":"null",
"uncom":"null",
"id":"death-note",
"data":"2023 жыл.",
"description":"Тылсым күштер, тергеушілер"
} ]
