[ {
"poster":"https://dopamine-app.github.io/api.dopamine.tv/server/img/death-note.png",
"title":"Ажал дәптері",
"title_orignal":"Death Note",
"age":"18+",
"works":"china",
"country":"Жапония, күз 2006 жыл",
"i_video":"37 бөлім. ~23 минут",
"status":"Көп бөлімді, шықты",
"studio":"Студия Madhouse, автор Цугуми Оба",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player, Custom-Player",
"note":"Анименің 1-бөлімі біздің телеграм арнада қолжетімді: t.me/dopaminevoice_full/19\n\nҚосымшаға жақын арада шығып қалады!",
"note_li":"null",
"info":"Орта мектеп оқушысы Лайт Ягамиге Ажал қызметшісі, яғни Шинигами, Рюктің дәптері қолына түседі. Осы дәптерге аты жазылған әрбір адам өледі, сондықтан Лайт Ягами жер бетіндегі зұлымдықпен күресуді шешеді.",
"announcement":"null",
"player":"null",
"unavailable":"null",
"comments":"null",
"key":"death-note",
"height":"null",
"uncom":"null",
"id":"death-note",
"data":"2023 жыл.",
"description":"Тылсым күштер, тергеушілер"
} ]
