[ {
"poster":"https://dopaminevoice.kz/img/kimi_poster.png",
"title":"Сенің есімің",
"title_orignal":"Kimi no na wa",
"age":"16+",
"country":"Жапония, 2016 жыл",
"i_video":"1 бөлім. ~116 минут",
"status":"Толықметражды, шықты",
"studio":"Студия Amuse, автор Макото Синкай",
"note":"null",
"note_li":"null",
"info":"Токио жігіті Таки мен провинциялық қыз Мицуханың арасында біртүрлі байланыс бар екенін білінеді. Түстерінде олар бір-бірінің өмірлерін сүреді. Бірақ бір күні бұл қабілет қалай пайда болса,солай кенеттен жоғалып кетеді. Таки ештеңеге қарамастан Мицуханы табуға бел буады.",
"unavailable":"null",
"comments":"https://vk.com/widget_comments.php?app=8140038&amp;width=100%25&amp;_ver=1&amp;limit=15&amp;height=0&amp;mini=auto&amp;norealtime=0&amp;page=0&amp;status_publish=0&amp;attach=&amp;url=https%3A%2F%2Fdopaminevoice.kz%2Fkimi_no_nawa&amp;title=%D0%A1%D0%B5%D0%BD%D1%96%D2%A3%20%D0%95%D1%81%D1%96%D0%BC%D1%96%D2%A3%20%7C%20Dopamine%20Voice&amp;description=Dopamine%20voice%20-%20%D0%A1%D0%B5%D0%BD%D1%96%D2%A3%20%D0%95%D1%81%D1%96%D0%BC%D1%96%D2%A3&amp;image=&amp;startWidth=363&amp;referrer=&amp;185da415f37",
"height":"2000",
"id":"kimi-no-na-wa",
"description":"фэнтези, драма",
"uncom":"null",
"announcement":"null",
"premium":"null",
"data":"null",
"statistics":"kimi-no-na-wa-s"
} ]
