[ {
"poster":"https://m.media-amazon.com/images/M/MV5BYTAzYzI1ZDYtNDUwYS00OTg4LTg4N2ItMTk5MTUxYzgyMGM4XkEyXkFqcGdeQXVyMTk2MDc1MjQ@._V1_.jpg",
"title":"Құрт жайлаған алқап",
"title_orignal":"Mojin: The Worm Valley",
"age":"18+",
"works":"china",
"country":"Қытай, 2018 жыл",
"i_video":"1 бөлім. ~1 сағат 50 минут",
"status":"Толықметражды, шықты",
"studio":"Студия? Автор?",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"null",
"note_li":"null",
"info":"Ежелгі дәуірді зерттеушілер тобы Юньнань провинциясының үңгірлеріне барады. Онда археологтар жоғалған қабірлерді, елестерді, тұзақтарды және, әрине, жауыз құбыжықтарды күтуде.",
"player":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"mojin-the-worm-valley",
"height":"null",
"uncom":"null",
"id":"mojin-the-worm-valley",
"data":"null",
"description":"шытырман оқиға, фантастика"
} ]
