[ {
"poster":"https://dopamine-app.github.io/api.dopamine.tv/server/img/sen-to-chihiro-no-kamikakushi.png",
"title":"Елес Ерткен",
"title_orignal":"Sen to Chihiro no Kamikakushi",
"age":"6+",
"works":"japan",
"country":"Жапония, 2001 жыл",
"i_video":"1 бөлім. ~125 минут",
"status":"Толықметражды, шықты",
"studio":"Студия Ghibli, режиссер Хаяо Миядзаки",
"available_player":"Қолжетімді бейне ойнатқыш табылмады:(",
"note":"Біздің келесі дыбыстама Ghibli студиясының ең үздік туындыларының бірі «Елес Ерткен (2001)» толықметражды анимесі болмақшы.\nТолық ақпарат: t.me/dopamine_voice/212",
"note_li":"null",
"info":"Чихиро анасы және әкесімен жаңа үйге көшіп барады.  Жолда адасып, олар таңғажайып дастархан күтіп тұрған бейтаныс шөлді қалаға тап болады. Чихироның ата-анасы ашкөздіктен тамақ жей бастаған кезде шошқаға айналып, зұлым сиқыршы Юбабаның тұтқынына айналады.  Енді сиқырлы жаратылыстар мен жұмбақ көріністердің арасында жалғыз қалған Чихиро ата-анасын қу кемпірдің сиқырынан қалай құтқару керектігін анықтауы керек.",
"announcement":"null",
"unavailable":"null",
"premium":"null",
"comments":"null",
"key":"sen-to-chihiro-no-kamikakushi",
"height":"null",
"uncom":"null",
"id":"sen-to-chihiro-no-kamikakushi",
"data":"2023 жыл.",
"description":"Шытырман оқиғалар, тылсым күштер"
} ]
