[ {
"poster":"https://yt3.googleusercontent.com/GKvzT2Xh4xpZ7hszNcSPAAuvdJYJgYeUBGik0cjmR2JnnXHaO3smdKvImDqixd-xxQQjF22aynY=s900-c-k-c0x00ffffff-no-rj",
"title":"Test Page",
"title_orignal":"Test Page",
"age":"0+",
"country":"Қазақстан, 2023 жыл",
"i_video":"0 бөлім. ~0 минут",
"status":"Шықты",
"studio":"Студия Dopamine Voice, автор Seele",
"note":"<b>Версия 3.12.19 (Caesium) - Beta</b><br/><a href=\"http://labx.mangawatcherx.com/api/v3/update/file?beta=true\">Нажмите для скачивания файла через браузер</a><br/>ВНИМАНИЕ!!! При любых проблемах - сообщайте по почте или в телеграмм канале <a href=\"https://t.me/joinchat/F9UM8VGcmjwrzIL6TRKf0Q\">LabX Talk</a><ul><li>Новое! - Nephila - Новые возможности парсинга</li><li>Тестовая поддержка перевода манги из архивов в GPU-based ридере</li><li>FIX! - Исправление ошибок и вылетов на основе отзывов пользователей</li></ul>",
"info":"Сипаттама берілген жоқ!",
"player":"null",
"comments":"",
"uncom":"null",
"key":"test",
"height":"5000",
"description": ["genre 1", "genre 2", "etc"],
"announcement":"null",
"data":"null",
"unavailable":"null",
"id":"test"
} ]
