{
"poster":"https://i.pinimg.com/originals/1b/19/e8/1b19e81f39e005d18c0b48956bf76b92.gif",
"title":"Siesta Chan",
"title_orignal":"Test Page",
"age":"18+",
"works":"unknown",
"country":"Kazakhstan, 2023 жыл",
"i_video":"? бөлім. ~ 00 минут",
"status":"?, ?",
"studio":"Студия Symphony, автор Seele?",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"Бұл бетті әзірлеуші ​​тестілеу үшін қосқан!",
"info":"Сипаттама берілген жоқ!",
"player":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"test",
"height":"null",
"uncom":"null",
"id":"test",
"data":"null",
"description":"test, test, test, test"
}
