[ {
"poster":"https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
"title":"Жүзіктер әміршісі",
"title_orignal":"The Lord of the Rings",
"age":"16+",
"works":"unknown",
"country":"Жаңа Зеландия, 2001 жыл",
"i_video":"1 бөлім. ~2 сағат 58 минут",
"status":"Толықметражды, шықты",
"studio":"Студия? Автор?",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"Барлық 2001, 2002, 2003 жылдары шыққан эпизодтары осы жерде қолжетімді!",
"info":"Сипаттама берілген жоқ!",
"player":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"the-lord-of-the-rings",
"height":"null",
"uncom":"null",
"id":"the-lord-of-the-rings",
"data":"null",
"description":"фэнтези, шытырман оқиғалар, драма"
} ]
