[ {
"poster":"https://upload.wikimedia.org/wikipedia/ru/1/19/Titanic_%28Official_Film_Poster%29.png",
"title":"Титаник",
"title_orignal":"Titanic",
"age":"16+",
"works":"japan",
"country":"АҚШ, 1997 жыл",
"i_video":"1 бөлім. ~3 сағат 14 минут",
"status":"Толықметражды, шықты",
"studio":"Автор Джеймс Кэмерон",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"null",
"note_li":"null",
"info":"Аты аңызға айналған лайнердің мәңгілікке суға батуы",
"player":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"titanic",
"height":"null",
"uncom":"null",
"id":"titanic",
"data":"null",
"description":"мелодрама, тарих, триллер, драма"
} ]
