[ {
"poster":"https://m.media-amazon.com/images/M/MV5BMTkwOTQ4OTg0OV5BMl5BanBnXkFtZTgwMzQyOTM0OTE@._V1_FMjpg_UX1000_.jpg",
"title":"Пусанға жол тартқан пойыз",
"title_orignal":"Train to Busan",
"age":"18+",
"works":"korea",
"country":"Оңтүстік Корея, 2016 жыл",
"i_video":"1 бөлім. ~2 сағат 43 минут",
"status":"Толықметражды, шықты",
"studio":"Режиссер Ён Сан Хо",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"null",
"note_li":"null",
"info":"Кішкентай Су-анның туған күні. Қыз әкесімен Сеулде тұрады және Пусандағы анасына барғысы келеді. Жолда күтпеген жағдай орын алып, елге жұмбақ вирус түседі. Қалай ойлайсың? олар бұл вирустан аман қала алады ма? Dopamine қосымшасынан бірге көрейік...",
"player":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"train-to-busan",
"height":"null",
"uncom":"null",
"id":"train-to-busan",
"data":"null",
"description":"ужасы, экшн, триллер"
} ]
