[ {
"poster":"https://avatars.mds.yandex.net/get-kinopoisk-image/4774061/6a901623-2d81-4398-a3b6-8b38b3c29659/600x900",
"title":"Әлсіз қаһарман",
"title_orignal":"Yakhan yeongung",
"age":"16+",
"works":"korea",
"country":"Оңтүстік Корея, 2022 жыл",
"i_video":"1/8 бөлім. ~45 минут",
"status":"Көп бөлімді, шықты",
"studio":"Режиссёр Ю Су-мин",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"",
"note_li":"null",
"info":"Сипаттама берілмеді...",
"premium":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"yakhan-yeongung",
"height":"null",
"uncom":"null",
"id":"yakhan-yeongung",
"data":"null",
"description":"драма, криминал"
} ]
