[ {
"poster":"https://sun9-36.userapi.com/impg/9gyYqq0IaY5Suajb5_H9uf--6qqAwZmJRRn_yA/DWZO8aWGKrY.jpg?size=424x604&quality=95&sign=5c78ec519bcc7e44b6ef91c4ba24c90a&type=album",
"title":"Аңдар Шаһары",
"title_orignal":"Zootopia",
"age":"6+",
"works":"usa",
"country":"АҚШ, 2016 жыл",
"i_video":"1 бөлім. ~108 минут",
"status":"Толықметражды, шықты",
"studio":"Режиссёр Байрон Ховард, Рич Мур, Джаред Буш",
"available_player":"Қолжетімді бейне ойнатқыш: Web-Player",
"note":"",
"note_li":"null",
"info":"Жануарлар өмір сүретін қала Аңдар шаһары деп аталады Бәрі сүтқоректілер мен жыртқыштар тату тәтті өмір сүреді. Шаһар жануарлардың өмір сүру ортасына сай түрлі аудандарға бөлінген. Қалада жаңа полиция офицері пайда болады, ол - көңілді қоян Жуди Хоппс. Өзін жақсы қырынан көрсетуге тырысқан қоян, қу түлкі Ник Уайлдпен бірге аса күрделі істі тергеуге кіріседі.",
"player":"null",
"unavailable":"null",
"announcement":"null",
"comments":"null",
"key":"zootopia",
"height":"null",
"uncom":"null",
"id":"zootopia",
"data":"null",
"description":"ізкесуші, аңдар мекені, фэнтези"
} ]
